---
title: "number of species with SNVs"
author: "sx"
date: "2024/11/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
library(ggbeeswarm)
library(ggplot2)
library(Hmisc)
library(ggsignif)
library(ggpubr)
library(RColorBrewer)
a<- read.table("SNV.txt",sep='\t', header=T)
a$time<-factor(a$time,levels=c("-7","0d","7d","14d","21d","28d"))

p<-ggplot(data=a,mapping=aes(x=group,y=Number, color=group,fill=group,color='black'))+scale_fill_manual(values=c("#d94b35", "#4cb0c8","#129880", "#3a5181", "#e9967c", "#808cae"))+stat_summary(fun = mean, geom="bar", width = 0.54, show.legend=F)+stat_summary(fun.data=mean_sdl, fun.args = list(mult=1/2),geom="errorbar", width=0.2,colour='black',show.legend=F)+geom_jitter(shape=21,fill="black",alpha=0.9,size=3,width = 0.12,col="black",show.legend=F)+theme_classic(  # 主题设置，这个是无线条主题
     base_line_size = 1 # 坐标轴的粗细
 )+
     theme(plot.title = element_text(size = 15,
                                     colour = "black",
                                     hjust = 0.5),
           axis.title.y = element_text(size = 15, 
                                       # family = "myFont", 
                                       color = "black",
                                       face = "bold", 
                                       vjust = 1.9, 
                                       hjust = 0.5, 
                                       angle = 90),
           legend.title = element_text(color="black", # 修改图例的标题
                                       size=15, 
                                       face="bold"),
           legend.text = element_text(color="black", # 设置图例标签文字
                                      size = 10, 
                                      face = "bold"),
           axis.text.x = element_text(size = 13,  # 修改X轴上字体大小，
                                      color = "black", # 颜色
                                      face = "bold", #  face取值：plain普通，bold加粗，italic斜体，bold.italic斜体加粗
                                      vjust = 0.5, # 位置
                                      hjust = 0.5, 
                                      angle = 0), #角度
           axis.text.y = element_text(size = 13,  
                                      color = "black",
                                      face = "bold", 
                                      vjust = 0.5, 
                                      hjust = 0.5, 
                                      angle = 0) 
     )
     p
     compare_means(Number~group, data=a, method = "wilcox.test", paired = T,  group.by = NULL)
